FROM python:3.10

ADD train_requirements.txt /root/requirements.txt
RUN pip install -r /root/requirements.txt

ADD train_main.py /root/
ADD trainer /root/trainer

WORKDIR /root

ENTRYPOINT ["python3", "train_main.py"]