namespace: rain-forecast-mlops
frontend:
  image: konglsh96/rain-forecast-mlops:front
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  service:
    ip: 192.168.49.2
    port: 31236
istio:
  ip: 192.168.49.2
  port: 31397
backend:
  ip: 192.168.49.2
  port: 8000
