namespace: rain-forecast-mlops
frontend:
  image: konglsh96/rain-forecast-mlops:front
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  service:
    ip: 192.168.49.2
    port: 31233
backend:
  image: konglsh96/rain-forecast-mlops:back
  ip: 192.168.49.2
  port: 30013
  train:
    cpu: 1
    memory: 1Gi
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
mmsisvc:
  resources:
    limits:
      cpu: 200m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 2Gi
istio:
  ip: 192.168.49.2
  port: 31397
mysql:
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi
  ip: 192.168.49.2
  port: 30007
  user: root
  password: root
  db: rain