apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rain-forecast-mlops-role
rules:
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "create", "get", "list", "watch", "delete" ]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete", "watch"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["trainedmodels"]
    verbs: ["get", "list", "create", "delete", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rain-forecast-mlops-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rain-forecast-mlops-role
subjects:
  - kind: ServiceAccount
    name: rain-forecast-mlops-sa
    namespace: {{ .Values.namespace }}
