apiVersion: v1
kind: Service
metadata:
  name: rain-forecast-mlops-front
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: rain-forecast-mlops-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.frontend.service.port }}
  type: NodePort
  externalIPs:
    - {{ .Values.frontend.service.ip }}

