apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: rain-multi-model
  namespace: {{ .Values.namespace }}
spec:
  predictor:
    containers:
      - env:
        - name: MULTI_MODEL_SERVER
          value: "true"
        - name: PYTHONBUFFERED
          value: "1"
        name: kserve-container
        image: konglsh96/rain-forecast-mlops:serving
        imagePullPolicy: Always
        resources:
          limits:
            cpu: {{ .Values.mmsisvc.resources.limits.cpu }}
            memory: {{ .Values.mmsisvc.resources.limits.memory }}
          requests:
            cpu: {{ .Values.mmsisvc.resources.requests.cpu }}
            memory: {{ .Values.mmsisvc.resources.requests.memory }}
